
services:
  client:
    build: ./client
    volumes:
      - type: bind
        source: ./client
        target: /app
    ports:
      - 3000:3000
    depends_on:
      - server

  server:
    build: ./server
    volumes:
      - type: bind
        source: ./server
        target: /app
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    image: postgres:16.3-alpine3.20
    restart: always
    environment:
      POSTGRES_USER: aram
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cinema
    ports:
      - 5432:5432